name: 'SchemaCrawler Action for GitHub Actions'
author: 'Sualeh Fatehi'
description: 'Run a SchemaCrawler command in the build pipeline'

branding:
  icon: database
  color: white

runs:
  using: docker
  image: docker://schemacrawler/schemacrawler-action:v16.15.1

outputs:
  exit_status:
    description: 'Exit status of the SchemaCrawler command-line run'
